# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: echo Running JMeter using Docker image
  displayName: 'Show what we are doing'
  
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
    
- script: |
    docker run --rm -v `pwd`/src/test/jmeter/:/jmeter:z egaillardon/jmeter-plugins -Jduration=30 -Jthreads=10 -Jrampup=10 -n -t mvn-demo.jmx -l result.csv -j jmeter.log -e -o report
    ls -ltr `pwd`/src/test/jmeter/
  displayName: 'Run JMeter in Docker'

- task: CopyFiles@2
  inputs:
    contents: '`pwd`/target/report/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: taurusArtifacts

