# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: echo Running JMeter with Taurus using Docker image
  displayName: 'Show what we are doing'
  
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
    
- script: |
    docker run --rm -v `pwd`/taurus:/bzt-configs -v `pwd`/taurus-artifacts:/tmp/artifacts blazemeter/taurus taurus-demo.yml
    ls -ltr `pwd`/taurus
    ls -ltr `pwd`/taurus-artifacts
  displayName: 'Run Taurus'

- task: CopyFiles@2
  inputs:
    contents: '`pwd`/taurus/taurus-artifacts/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: taurusArtifacts

